// Auto-generated by tools/dialogue_yaml_to_c.py
// Do not edit by hand.
#ifndef AME_DIALOGUE_GENERATED_H
#define AME_DIALOGUE_GENERATED_H
#include <stddef.h>
#include "ame_dialogue.h"
#define AME_HAVE_GENERATED_DIALOGUES 1
extern const AmeDialogueScene *ame__generated_scenes[];
extern const size_t ame__generated_scenes_count;
#endif
