// Auto-generated by tools/dialogue_yaml_to_c.py
// Do not edit by hand.
#include "ame_dialogue.h"
#include <stddef.h>

static const AmeDialogueLine annoying_lines[] = {
    { "start", "Venera", "Oh.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { NULL, "Venera", "I dislike that part.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { NULL, "Venera", "So annoying.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { NULL, "Glitcher", "I am a bit worried.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { NULL, "Glitcher", "Are you really a racer to", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { NULL, "Glitcher", "to pass such callenge", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { NULL, "Glitcher", "without breaking me?", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { NULL, "Venera", "Don't be afraid,", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { NULL, "Venera", "fall or flip damage", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { NULL, "Venera", "was not added to this game.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { NULL, "Glitcher", "Splendid.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
};

static const AmeDialogueScene scene_annoying = { .scene="annoying", .lines=annoying_lines, .line_count=sizeof(annoying_lines)/sizeof(annoying_lines[0]) };

static const AmeDialogueLine introduction_lines[] = {
    { "start", "Glitcher", "Hi. Press ENTER to proceed.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { NULL, "Glitcher", "How is your day?", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { NULL, "Glitcher", "Controls are WS, or up-down acceleration", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { NULL, "Glitcher", "AD, left-right yaw", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { NULL, "Glitcher", "So. We have a good life over there.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { "end", "Guide", "Okay, have fun!", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
};

static const AmeDialogueScene scene_introduction = { .scene="introduction", .lines=introduction_lines, .line_count=sizeof(introduction_lines)/sizeof(introduction_lines[0]) };

static const AmeDialogueLine platforming_lines[] = {
    { "start", "Venera", "Ah. I like jumps", NULL, NULL, NULL, NULL, "unlock_car_jump", NULL, NULL, NULL, 0 },
    { NULL, "Glitcher", "Are you sure", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { NULL, "Venera", "that it is fun?", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { NULL, "Venera", "With sufficient skill", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { NULL, "Venera", "anything can be fun.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { NULL, "Glitcher", "'Anything' is a key word", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { NULL, "Glitcher", "here. But I enjoy jumps.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { NULL, "Glitcher", "Feeling of road on wheels.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { NULL, "Glitcher", "Hops and dreams.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { NULL, "Glitcher", "But I like food more.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { NULL, "Glitcher", "When we are going to eat more?", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
};

static const AmeDialogueScene scene_platforming = { .scene="platforming", .lines=platforming_lines, .line_count=sizeof(platforming_lines)/sizeof(platforming_lines[0]) };

static const AmeDialogueLine enableJump_lines[] = {
    { "start", "Glitcher", "Wow! That cookie", NULL, NULL, NULL, NULL, "unlock_car_jump", NULL, NULL, NULL, 0 },
    { NULL, "Glitcher", "gave me ability", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { NULL, "Glitcher", "to jump.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
};

static const AmeDialogueScene scene_enableJump = { .scene="enableJump", .lines=enableJump_lines, .line_count=sizeof(enableJump_lines)/sizeof(enableJump_lines[0]) };

const AmeDialogueScene *ame__generated_scenes[] = {
    &scene_annoying,
    &scene_introduction,
    &scene_platforming,
    &scene_enableJump,
};

const size_t ame__generated_scenes_count = sizeof(ame__generated_scenes)/sizeof(ame__generated_scenes[0]);
