// Auto-generated by tools/dialogue_yaml_to_c.py
// Do not edit by hand.
#include "ame_dialogue.h"
#include <stddef.h>

static const AmeDialogueLine introduction_lines[] = {
    { "start", "Glitcher", "Hi.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { NULL, "Glitcher", "How is your day?", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { NULL, "Glitcher", "Controls are WS, or up-down acceleration", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { NULL, "Glitcher", "AD, left-right yaw", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { NULL, "Glitcher", "So. We have a good life over there.", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
    { "end", "Guide", "Okay, have fun!", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 },
};

static const AmeDialogueScene scene_introduction = { .scene="introduction", .lines=introduction_lines, .line_count=sizeof(introduction_lines)/sizeof(introduction_lines[0]) };

const AmeDialogueScene *ame__generated_scenes[] = {
    &scene_introduction,
};

const size_t ame__generated_scenes_count = sizeof(ame__generated_scenes)/sizeof(ame__generated_scenes[0]);
