name: Build Game on Multiple Platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [Release]
        include:
          # Ubuntu GNU
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          # Ubuntu Clang
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
          # macOS uses Apple Clang
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
          # Windows MSVC (use VS generator)
          - os: windows-latest
            vs_generator: "Visual Studio 17 2022"
            arch: x64

    steps:
    - uses: actions/checkout@v4

    # Linux build deps so SDL can enable Wayland/KMSDRM backends
    - name: Install Linux build dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libdrm-dev libgbm-dev libudev-dev \
          libwayland-dev wayland-protocols libxkbcommon-dev libdecor-0-dev \
          libpulse-dev libpipewire-0.3-dev

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake (Linux/macOS)
      if: matrix.os != 'windows-latest'
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DBUILD_BUNDLED_SDL=ON
        -S ${{ github.workspace }}

    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }} \
        -G "${{ matrix.vs_generator }}" -A ${{ matrix.arch }} \
        -DBUILD_BUNDLED_SDL=ON \
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}

    - name: Copy Assets to Build Directory
      shell: bash
      run: |
        cp -r ${{ github.workspace }}/Assets ${{ steps.strings.outputs.build-output-dir }}/Assets

    - name: Create Zip Archive
      shell: bash
      run: |
        cd ${{ steps.strings.outputs.build-output-dir }}
        zip -r ${{ github.workspace }}/game-${{ matrix.os }}-${{ matrix.build_type }}.zip .

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: game-${{ matrix.os }}-${{ matrix.build_type }}
        path: ${{ github.workspace }}/game-${{ matrix.os }}-${{ matrix.build_type }}.zip
